from icfes.settings import DATA_PATH_TEXT, PARQUET_PATH

__all__ = ["DATA_PATH_TEXT", "PARQUET_PATH", "MAP_ATTR_BASE", "MAP_ATTR_ICFES"]

MAP_ATTR_BASE = {
    "periodo": "periodo",
    "estu_consecutivo": "estu_consecutivo",
    "cole_area_ubicacion": "cole_area_ubicacion",
    "cole_bilingue": "cole_bilingue",
    "cole_calendario": "cole_calendario",
    "cole_caracter": "cole_caracter",
    "cole_codigo_icfes": "cole_codigo_icfes",
    "cole_depto_ubicacion": "cole_depto_ubicacion",
    "cole_genero": "cole_genero",
    "cole_jornada": "cole_jornada",
    "cole_mcpio_ubicacion": "cole_mcpio_ubicacion",
    "cole_naturaleza": "cole_naturaleza",
    "cole_nombre_establecimiento": "cole_nombre_establecimiento",
    "cole_nombre_sede": "cole_nombre_sede",
    "desemp_c_naturales": "desemp_c_naturales",
    "desemp_ingles": "desemp_ingles",
    "desemp_lectura_critica": "desemp_lectura_critica",
    "desemp_matematicas": "desemp_matematicas",
    "desemp_sociales_ciudadanas": "desemp_sociales_ciudadanas",
    "estu_depto_reside": "estu_depto_reside",
    "estu_discapacidad": "estu_discapacidad",
    "estu_fechanacimiento": "estu_fechanacimiento",
    "estu_genero": "estu_genero",
    "estu_mcpio_reside": "estu_mcpio_reside",
    "estu_nse_establecimiento": "estu_nse_establecimiento",
    "estu_nse_individual": "estu_nse_individual",
    "estu_pais_reside": "estu_pais_reside",
    "estu_tieneetnia": "estu_tieneetnia",
    "fami_educacionmadre": "fami_educacionmadre",
    "fami_educacionpadre": "fami_educacionpadre",
    "fami_estratovivienda": "fami_estratovivienda",
    "fami_tieneinternet": "fami_tieneinternet",
    "punt_c_naturales": "punt_c_naturales",
    "punt_global": "punt_global",
    "punt_ingles": "punt_ingles",
    "punt_lectura_critica": "punt_lectura_critica",
    "punt_matematicas": "punt_matematicas",
    "punt_sociales_ciudadanas": "punt_sociales_ciudadanas",
    "estu_grupoetnia": "estu_etnia",
}

MAP_ATTR_ICFES = {
    "Examen_Saber_11_20151": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20152": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20161": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20162": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20171": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20172": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20181": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20182": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20191": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20192": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20201": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20202": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20211": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20212": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20221": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20222": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20231": {**MAP_ATTR_BASE},
    "Examen_Saber_11_20232": {**MAP_ATTR_BASE, "estu_grupoetnia": "estu_grupoetnia"},
    "Examen_Saber_11_20241": {**MAP_ATTR_BASE, "estu_grupoetnia": "estu_grupoetnia"},
    "Examen_Saber_11_20242": {**MAP_ATTR_BASE, "estu_grupoetnia": "estu_grupoetnia"},
    "Examen_Saber_11_20251": {**MAP_ATTR_BASE, "estu_grupoetnia": "estu_grupoetnia"},
    "Examen_Saber_11_20252": {**MAP_ATTR_BASE, "estu_grupoetnia": "estu_grupoetnia"},
}
